maintainers:
- doob187
- fscorrupt
- DrAg0n141
labels: true
empty_description_check:
  enabled: true
  enforced: false
branch_destroyer:
  enabled: true
  protected_branches:
  - master
pull_requests:
  automated_merge: false
  cats_enabled: true
  dogs_enabled: true
  allow_approval: true
