name: Rebase

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  rebase:
    runs-on: ubuntu-20.04
    steps:
      - uses: peter-evans/rebase@v2
        with:
          base: master
