name: Rebase

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'apps/**'
    - 'base/**'
    - 'nightly/**'

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/rebase@v2
        with:
          base: master
