name: Get latest versions

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */2 * * *"

permissions: read-all

jobs:
  get-version:
    runs-on: self-hosted
    permissions:
      packages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: 0
        clean: false

    - name: Run Test & Get New Versions
      run: |
        echo "Fetch new Versions"
        if test -f "./.templates/ci/version.sh"; then
           bash "./.templates/ci/version.sh"
        fi
      env:
        username: ${{ github.actor }}
        token: ${{ secrets.CR_PAT }}

  run-crf:
    runs-on: self-hosted
    needs: 
    - get-version
    permissions:
      packages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: 0
        clean: false

    - name: Run CRLF changes
      run: |
        echo "Fixxing endings"
        if test -f "./.templates/ci/crlf.sh"; then
           bash "./.templates/ci/crlf.sh"
        fi

  contrib:
    runs-on: ubuntu-20.04
    needs: 
    - get-version
    - run-crf
    permissions:
      packages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CR_PAT }}
        fetch-depth: 0
        clean: true

    - uses: BobAnkh/add-contributors@master
      with:
        REPO_NAME: 'dockserver/container'
        CONTRIBUTOR: '### Contributors'
        COLUMN_PER_ROW: '4'
        ACCESS_TOKEN: ${{ secrets.CR_PAT }}
        IMG_WIDTH: '50'
        FONT_SIZE: '14'
        PATH: '/README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'round'
